
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fituoswwkbfzrrhaqjix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpdHVvc3d3a2JmenJyaGFxaml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjI0MDIsImV4cCI6MjA1OTQzODQwMn0.XHGjQhV0cyELyb9XZkAjkH4ahHdvI2EEpc9ScLW0k4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
